import "./style.scss"
import "./scripts/apiHealth"
import "./scripts/apiWorld"
import "./scripts/apiScience"
import "./scripts/apiBusiness"
import "./scripts/apiTravel"
import "./scripts/darkmode"
import "./scripts/settings"
import "./scripts/newsboxCategories"

